apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warehouse-platform.name" . }}-secrets
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
