apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "warehouse-platform.name" . }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "warehouse-platform.name" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "warehouse-platform.name" . }}-web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: http://{{ include "warehouse-platform.name" . }}-api:8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-platform.name" . }}-web
spec:
  selector:
    app: {{ include "warehouse-platform.name" . }}-web
  ports:
    - port: 3000
      targetPort: 3000

